version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade --force-reinstall "botocore>1.21.30" "boto3>1.18.30" "awscli>1.20.30"

  build:
    commands:
      - current_date=$(echo $CODEBUILD_BUILD_ID | grep -o '[0-9]\{8\}')-$(date '+%Y-%d-%m-%H-%M-%S')
      - python builder.py --function-name "weather" --model-execution-role "$MODEL_EXECUTION_ROLE_ARN" --model-name "weather-${current_date}" --model-package-group-name "weather-forecast-hourly" --sagemaker-project-id "$SAGEMAKER_PROJECT_ID" --sagemaker-project-name "$SAGEMAKER_PROJECT_NAME" --s3-bucket "$ARTIFACT_BUCKET" --export-staging-config $EXPORT_TEMPLATE_STAGING_CONFIG --export-prod-config $EXPORT_TEMPLATE_PROD_CONFIG
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket cw-sam-example
      - sam deploy --template-file package.yml --stack-name weather-batch-transform --capabilities CAPABILITY_IAM --parameter-overrides ExecutionRoleArn="$MODEL_EXECUTION_ROLE_ARN" ModelNameParameter=weather-${current_date}


      # Print the files to verify contents
      - cat $EXPORT_TEMPLATE_STAGING_CONFIG
      - cat $EXPORT_TEMPLATE_PROD_CONFIG
      
artifacts:
  files:
    - package.yml
    - $EXPORT_TEMPLATE_NAME
    - $EXPORT_TEMPLATE_STAGING_CONFIG
    - $EXPORT_TEMPLATE_PROD_CONFIG
