AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions

Resources:
  Model:
    Type: AWS::SageMaker::Model
    Properties:
      Containers:
         - ModelPackageName: !Ref model_package_name
      ExecutionRoleArn: !Ref execution_role_arn
      
  weather:
    Type: AWS::Serverless::Function
    Properties:
      Handler: weather.lambda.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Description: 'Automatically loaded weather batch transform job.'
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python37:5
      AutoPublishAlias: live
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: '*'
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: !Ref beforeAllowTraffic
          PostTraffic: !Ref afterAllowTraffic

  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: beforeAllowTraffic.handler
      Runtime: nodejs16.x
      FunctionName: 'CodeDeployHook_beforeAllowTraffic'
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
              Resource: !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: !Ref weather.Version
      Environment:
        Variables:
          NewVersion: !Ref weather.Version

  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: afterAllowTraffic.handler
      Runtime: nodejs16.x
      FunctionName: 'CodeDeployHook_afterAllowTraffic'
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
              Resource: !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: !Ref weather.Version
      Environment:
        Variables:
          NewVersion: !Ref weather.Version
