AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample SAM template for deploying Lambda functions

Parameters:
  ExecutionRoleArn:
    Type: String
    Description: Enter the ARN of the execution role for the SageMaker Model
  ModelNameParameter:
    Type: String
    Description: Enter the name of the model

Resources:
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ExecutionRoleArn: !Ref ExecutionRoleArn
      ModelName: !Ref ModelNameParameter

  weather:
    Type: AWS::Serverless::Function
    Properties:
      Handler: weather.lambda.lambda_handler
      Runtime: python3.7
      Timeout: 300
      Description: 'Automatically loaded weather batch transform job.'
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python37:5
      AutoPublishAlias: live
      Policies:
        - Statement:
            - Effect: Allow
              Action: lambda:InvokeFunction
              Resource: '*'
            - S3CrudPolicy:
              BucketName: cw-weather-data-deployment
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: !Ref beforeAllowTraffic
          PostTraffic: !Ref afterAllowTraffic

  beforeAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: beforeAllowTraffic.handler
      Runtime: nodejs16.x
      FunctionName: 'CodeDeployHook_beforeAllowTraffic'
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
              Resource: !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: !Ref weather.Version
      Environment:
        Variables:
          NewVersion: !Ref weather.Version

  afterAllowTraffic:
    Type: AWS::Serverless::Function
    Properties:
      Handler: afterAllowTraffic.handler
      Runtime: nodejs16.x
      FunctionName: 'CodeDeployHook_afterAllowTraffic'
      DeploymentPreference:
        Enabled: false
      Timeout: 5
      Policies:
        - Version: "2012-10-17"
          Statement: 
            - Effect: "Allow"
              Action: 
                - "codedeploy:PutLifecycleEventHookExecutionStatus"
              Resource: !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
            - Effect: "Allow"
              Action: 
                - "lambda:InvokeFunction"
              Resource: !Ref weather.Version
      Environment:
        Variables:
          NewVersion: !Ref weather.Version
